# Ordinal Encoding

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
23   96  Female     Good    School        No
13   57  Female  Average    School        No
41   23    Male     Good        PG       Yes
1    68  Female     Poor        UG        No
24   16  Female  Average        PG       Yes

In [4]:
df = df[['review', 'education', 'purchased']]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
df['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [7]:
df['education'].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

## Ordinal Encoder

In [24]:
from sklearn.preprocessing import OrdinalEncoder

In [25]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'],['School', 'UG', 'PG']])

In [26]:
x_train = df[['review', 'education']]

In [27]:
x_train.head()

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

In [28]:
oe.fit(x_train)
x_train = oe.transform(x_train)

In [29]:
x_train = pd.DataFrame(x_train, columns=['review', 'education'])

In [30]:
x_train.head()

   review  education
0     1.0        0.0
1     0.0        1.0
2     2.0        2.0
3     2.0        2.0
4     1.0        1.0

In [31]:
x_train['review'].value_counts()

review
0.0    18
2.0    18
1.0    14
Name: count, dtype: int64

In [32]:
x_train['education'].value_counts()

education
2.0    18
0.0    16
1.0    16
Name: count, dtype: int64

In [36]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [37]:
from sklearn.preprocessing import LabelEncoder

In [38]:
le = LabelEncoder()

In [39]:
y_train = df['purchased']

In [40]:
le.fit(y_train)

LabelEncoder()

In [41]:
y_train = le.transform(y_train)

In [42]:
y_train = pd.DataFrame(y_train, columns=['purchased'])

In [43]:
y_train.sample(10)

    purchased
43          0
31          1
3           0
40          0
10          1
34          0
22          1
12          0
27          0
15          0

In [46]:
le.classes_

array(['No', 'Yes'], dtype=object)